### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by ImBoing** [Androz2091/discord-giveaways-bot#36]
When ever a giveaway ends this error keeps getting logged in console over and over again  `(node:10791) UnhandledPromiseRejectionWarning: Unable to fetch message with ID 715223127902126135. (node:10791) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 23) `

**Comment by Androz2091** [comment]
I will try to reproduce this

**Comment by boingfromdiscord** [comment]
is there any lead yet? Because its kind of annoying

**Comment by boingfromdiscord** [comment]
Hello it seems to be this line that is causing the error `await this.fetchMessage().catch(() => {});`. Now it doesnt end the giveaway for some reason? @Androz2091

**Comment by Androz2091** [comment]
this has been fixed
