### ISSUE TITLE
Timer glitch

### ISSUE THREAD

**Issue by y8erwgerubohceurv** [Androz2091/discord-giveaways-bot#39]
Hello, I was experimenting and I realised that the timer on the giveaway for me is a little bit delayed I have set it to update every 5 sec but in the beginning right after running the command it waits like 10 to 15 sec before starting. Like the timer is very slow and it is not updating every 5ms

**Comment by Androz2091** [comment]
Hello
This can be due to your internet connection. Can you try to increase the timer interval?

**Comment by Androz2091** [comment]
this has been fixed
