### ISSUE TITLE
No participations

### ISSUE THREAD

**Issue by invaliduser231** [Androz2091/discord-giveaways-bot#53]
if i start a giveaway, it doesnt count any reactions

**Comment by NicoHd105** [comment]
You mean in the end no winner is choosen? Because if thats the case check if you have the latest discord.js version with `npm outdated` and update it if needed because in 12.3.0 there was something that caused that for me too, which was fixed in 12.3.1

**Comment by Nico105** [comment]
> if i start a giveaway, it doesnt count any reactions

Try installing the latest `discord-giveaways` version and see if it fixes it
