### ISSUE TITLE
The count must be a number.

### ISSUE THREAD

**Issue by JaquelineQC** [Androz2091/discord-giveaways-bot#54]
Hello, I've got an error when the giveaway is supposed to end: 
`(node:15844) UnhandledPromiseRejectionWarning: TypeError: The count must be a number.
    at Map.random (C:\Users\--\Desktop\--\node_modules\discord.js\src\util\Collection.js:134:42)
    at Giveaway.roll (C:\Users\--\Desktop\--\node_modules\discord-giveaways\src\Giveaway.js:304:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\--\Desktop\--\node_modules\discord-giveaways\src\Giveaway.js:354:27
(node:15844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)`

**Comment by Nico105** [comment]
Try installing the latest `discord-giveaways` version and see if it fixes it
