### ISSUE TITLE
UnhandledPromiseRejectionWarning Error

### ISSUE THREAD

**Issue by officialrolly** [Androz2091/discord-giveaways-bot#59]
How can I fix this error? I got the errors while starting up the bot as well as starting giveaways. It doesn't show the giveaway embed up, only for the Giveaway started in channel.
```
(node:9292) UnhandledPromiseRejectionWarning: SyntaxError: The storage file is not properly formatted (Unexpected end of JSON input).
    at GiveawaysManager.getAllGiveaways (C:\Users\user\Desktop\giveaways-bot-master\node_modules\discord-giveaways\src\Manager.js:308:27)
    at async GiveawaysManager._init (C:\Users\user\Desktop\giveaways-bot-master\node_modules\discord-giveaways\src\Manager.js:391:30)
(node:9292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

Thanks!

**Comment by needhamgary** [comment]
Make sure you have the proper ending in the storage location.  Aka `}`

**Comment by Nico105** [comment]
> How can I fix this error? I got the errors while starting up the bot as well as starting giveaways. It doesn't show the giveaway embed up, only for the Giveaway started in channel.
> 
> ```
> (node:9292) UnhandledPromiseRejectionWarning: SyntaxError: The storage file is not properly formatted (Unexpected end of JSON input).
>     at GiveawaysManager.getAllGiveaways (C:\Users\user\Desktop\giveaways-bot-master\node_modules\discord-giveaways\src\Manager.js:308:27)
>     at async GiveawaysManager._init (C:\Users\user\Desktop\giveaways-bot-master\node_modules\discord-giveaways\src\Manager.js:391:30)
> (node:9292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> ```
> 
> Thanks!

Do you still face this issue? If not, please provide your conclusion/solution and close this issue. If yes, have you made sure that your `giveaways.json` file looks the same like the default bot?
