### ISSUE TITLE
TypeError when there isn't enough participants in giveaway

### ISSUE THREAD

**Issue by Hakunek** [Androz2091/discord-giveaways-bot#76]
when there is set more winners than there are participants
it returns this error:
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined`

Location of errors:
    at Giveaway.checkWinnerEntry (D:\------\node_modules\discord-giveaways\src\Giveaway.js:302:42)
    at Giveaway.roll (D:\------\node_modules\discord-giveaways\src\Giveaway.js:333:45)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async D:\------\node_modules\discord-giveaways\src\Giveaway.js:400:29

example:
like giveaway is set for 2 or more winners
but there is one participant

ss with proof:
![image](https://user-images.githubusercontent.com/51033858/105606169-0a0d7b80-5d98-11eb-9451-a5c77cb80099.png)
![image](https://user-images.githubusercontent.com/51033858/105606202-4214be80-5d98-11eb-84fa-d96d8e202584.png)

**Comment by Androz2091** [comment]
this has been fixed
