### ISSUE TITLE
Bot isn't starting.

### ISSUE THREAD

**Issue by FantonFancy** [Androz2091/discord-giveaways-bot#97]
`                giveaway.message ??= await giveaway.fetchMessage().catch(() => {});
                                 ^^^

SyntaxError: Unexpected token '??='
[90m    at wrapSafe (internal/modules/cjs/loader.js:979:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1027:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:88:18)[39m
    at Object.<anonymous> (C:\Users\Dima\Desktop\GiveawayBot\node_modules\[4mdiscord-giveaways[24m\index.js:3:23)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m`

**Comment by DevKilioZOfficiel** [comment]
I have this same problem, with my serverid and my bot id

**Comment by Nico105** [comment]
I remembered: https://github.com/Androz2091/discord-giveaways-bot/issues/92#issuecomment-914492311
