### ISSUE TITLE
{BUG/ERROR} Giveaways Drop crash

### ISSUE THREAD

**Issue by GeistFighter** [Androz2091/discord-giveaways-bot#99]
Hey,

When I run a Drop Giveaways, if a user with the exclude role adds a reaction, the Giveaways counter stops with an error.

**Comment by Nico105** [comment]
the error would be?

**Comment by GeistFighter** [comment]
The error is that it sets the "noWinner" variable directly, so the Giveaway stops, the error is the "noWinner", i don't have a real error, I don't know if that is clear?

**Comment by Nico105** [comment]
So only 1 person reacted?

**Comment by GeistFighter** [comment]
In fact, the problem is that when a person who is normally part of the exclusions reacts, he is counted in the drop as a person who reacts, but is not counted in the fact that he can win, so if there is only one winner on the drop, if the 1st to add the reaction is a person who is part of the exclusions, the drop stops because it takes him into account, but indicates the "NoWinner" because he is excluded, so it would be necessary that the exclusions are also applied to the counter of the Drop reaction.

On the other hand, if there are several winners in the drop, if among the winners there are people excluded, the number of winners will not be equal to the number of winners set.

**Comment by GeistFighter** [comment]
Oh bruh, I just noticed it now, I opened the bug on the Github of the bot, but it concerns the package itself

**Comment by GeistFighter** [comment]
https://github.com/Androz2091/discord-giveaways/issues/429
